#!/bin/bash

echo "📦 Creating deployment package for Cloud Shell..."
echo ""

cd /Users/krypton/kryptonprojects/UI/backend-cloud-run

echo "Files created:"
echo "  ✅ index.js (Full backend with sorting & filtering)"
echo "  ✅ package.json (Dependencies)"
echo "  ✅ deploy.sh (Deployment script)"
echo ""
echo "📤 Next Steps:"
echo ""
echo "1. In Cloud Shell, run:"
echo "   ------------------------"
echo "   mkdir -p ~/backend-cloud-run"
echo "   cd ~/backend-cloud-run"
echo ""
echo "2. Copy these files to Cloud Shell:"
echo "   - Click the 3-dot menu in Cloud Shell"
echo "   - Select 'Upload'"
echo "   - Upload: index.js and package.json"
echo ""
echo "   OR use Cloud Shell Editor:"
echo "   - Click 'Open Editor' in Cloud Shell"
echo "   - Create files manually and paste content"
echo ""
echo "3. Deploy:"
echo "   ------------------------"
echo "   gcloud config set project beyond-cloud-477013"
echo "   gcloud run deploy darkweb-api \\"
echo "     --source . \\"
echo "     --region us-central1 \\"
echo "     --allow-unauthenticated \\"
echo "     --set-env-vars CLOUD_SQL_CONNECTION=beyond-cloud-477013:us-central1:darkweb-db,DB_USER=api_user,DB_NAME=threat_intelligence \\"
echo "     --set-secrets DB_PASSWORD=db-password:latest \\"
echo "     --add-cloudsql-instances beyond-cloud-477013:us-central1:darkweb-db"
echo ""
echo "4. Wait 3-5 minutes for deployment"
echo ""
echo "5. Refresh your dashboard at: http://localhost:3002/darkweb-mentions"
echo ""
echo "✅ Then sorting and date filtering will work perfectly!"
echo ""

# Show file locations
echo "Files are ready at:"
echo "  $(pwd)/index.js"
echo "  $(pwd)/package.json"
echo "  $(pwd)/deploy.sh"
